// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: internal/pb/contextiq.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoPath      string                 `protobuf:"bytes,1,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexRequest) Reset() {
	*x = IndexRequest{}
	mi := &file_internal_pb_contextiq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexRequest) ProtoMessage() {}

func (x *IndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_contextiq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexRequest.ProtoReflect.Descriptor instead.
func (*IndexRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_contextiq_proto_rawDescGZIP(), []int{0}
}

func (x *IndexRequest) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

type IndexResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FilesIndexed   int32                  `protobuf:"varint,3,opt,name=files_indexed,json=filesIndexed,proto3" json:"files_indexed,omitempty"`
	SymbolsIndexed int32                  `protobuf:"varint,4,opt,name=symbols_indexed,json=symbolsIndexed,proto3" json:"symbols_indexed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IndexResponse) Reset() {
	*x = IndexResponse{}
	mi := &file_internal_pb_contextiq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexResponse) ProtoMessage() {}

func (x *IndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_contextiq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexResponse.ProtoReflect.Descriptor instead.
func (*IndexResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_contextiq_proto_rawDescGZIP(), []int{1}
}

func (x *IndexResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IndexResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *IndexResponse) GetFilesIndexed() int32 {
	if x != nil {
		return x.FilesIndexed
	}
	return 0
}

func (x *IndexResponse) GetSymbolsIndexed() int32 {
	if x != nil {
		return x.SymbolsIndexed
	}
	return 0
}

type OptimizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	OpenFiles     []string               `protobuf:"bytes,2,rep,name=open_files,json=openFiles,proto3" json:"open_files,omitempty"`
	CursorFile    string                 `protobuf:"bytes,3,opt,name=cursor_file,json=cursorFile,proto3" json:"cursor_file,omitempty"`
	CursorLine    int32                  `protobuf:"varint,4,opt,name=cursor_line,json=cursorLine,proto3" json:"cursor_line,omitempty"`
	RepoPath      string                 `protobuf:"bytes,5,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,6,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizeRequest) Reset() {
	*x = OptimizeRequest{}
	mi := &file_internal_pb_contextiq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeRequest) ProtoMessage() {}

func (x *OptimizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_contextiq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeRequest.ProtoReflect.Descriptor instead.
func (*OptimizeRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_contextiq_proto_rawDescGZIP(), []int{2}
}

func (x *OptimizeRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *OptimizeRequest) GetOpenFiles() []string {
	if x != nil {
		return x.OpenFiles
	}
	return nil
}

func (x *OptimizeRequest) GetCursorFile() string {
	if x != nil {
		return x.CursorFile
	}
	return ""
}

func (x *OptimizeRequest) GetCursorLine() int32 {
	if x != nil {
		return x.CursorLine
	}
	return 0
}

func (x *OptimizeRequest) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *OptimizeRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

type OptimizeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CompressedPrompt string                 `protobuf:"bytes,1,opt,name=compressed_prompt,json=compressedPrompt,proto3" json:"compressed_prompt,omitempty"`
	TokenSavings     float64                `protobuf:"fixed64,2,opt,name=token_savings,json=tokenSavings,proto3" json:"token_savings,omitempty"`
	RawTokens        int32                  `protobuf:"varint,3,opt,name=raw_tokens,json=rawTokens,proto3" json:"raw_tokens,omitempty"`
	OptimizedTokens  int32                  `protobuf:"varint,4,opt,name=optimized_tokens,json=optimizedTokens,proto3" json:"optimized_tokens,omitempty"`
	IncludedSymbols  []string               `protobuf:"bytes,5,rep,name=included_symbols,json=includedSymbols,proto3" json:"included_symbols,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OptimizeResponse) Reset() {
	*x = OptimizeResponse{}
	mi := &file_internal_pb_contextiq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeResponse) ProtoMessage() {}

func (x *OptimizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_contextiq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeResponse.ProtoReflect.Descriptor instead.
func (*OptimizeResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_contextiq_proto_rawDescGZIP(), []int{3}
}

func (x *OptimizeResponse) GetCompressedPrompt() string {
	if x != nil {
		return x.CompressedPrompt
	}
	return ""
}

func (x *OptimizeResponse) GetTokenSavings() float64 {
	if x != nil {
		return x.TokenSavings
	}
	return 0
}

func (x *OptimizeResponse) GetRawTokens() int32 {
	if x != nil {
		return x.RawTokens
	}
	return 0
}

func (x *OptimizeResponse) GetOptimizedTokens() int32 {
	if x != nil {
		return x.OptimizedTokens
	}
	return 0
}

func (x *OptimizeResponse) GetIncludedSymbols() []string {
	if x != nil {
		return x.IncludedSymbols
	}
	return nil
}

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	OpenFiles     []string               `protobuf:"bytes,4,rep,name=open_files,json=openFiles,proto3" json:"open_files,omitempty"`
	CursorFile    string                 `protobuf:"bytes,5,opt,name=cursor_file,json=cursorFile,proto3" json:"cursor_file,omitempty"`
	CursorLine    int32                  `protobuf:"varint,6,opt,name=cursor_line,json=cursorLine,proto3" json:"cursor_line,omitempty"`
	RepoPath      string                 `protobuf:"bytes,7,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,8,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_internal_pb_contextiq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_contextiq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_contextiq_proto_rawDescGZIP(), []int{4}
}

func (x *ChatRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ChatRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ChatRequest) GetOpenFiles() []string {
	if x != nil {
		return x.OpenFiles
	}
	return nil
}

func (x *ChatRequest) GetCursorFile() string {
	if x != nil {
		return x.CursorFile
	}
	return ""
}

func (x *ChatRequest) GetCursorLine() int32 {
	if x != nil {
		return x.CursorLine
	}
	return 0
}

func (x *ChatRequest) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *ChatRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

type ChatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Response        string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	OptimizedTokens int32                  `protobuf:"varint,2,opt,name=optimized_tokens,json=optimizedTokens,proto3" json:"optimized_tokens,omitempty"`
	RawTokens       int32                  `protobuf:"varint,3,opt,name=raw_tokens,json=rawTokens,proto3" json:"raw_tokens,omitempty"`
	TokenSavings    float64                `protobuf:"fixed64,4,opt,name=token_savings,json=tokenSavings,proto3" json:"token_savings,omitempty"`
	FromCache       bool                   `protobuf:"varint,5,opt,name=from_cache,json=fromCache,proto3" json:"from_cache,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_internal_pb_contextiq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_contextiq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_contextiq_proto_rawDescGZIP(), []int{5}
}

func (x *ChatResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *ChatResponse) GetOptimizedTokens() int32 {
	if x != nil {
		return x.OptimizedTokens
	}
	return 0
}

func (x *ChatResponse) GetRawTokens() int32 {
	if x != nil {
		return x.RawTokens
	}
	return 0
}

func (x *ChatResponse) GetTokenSavings() float64 {
	if x != nil {
		return x.TokenSavings
	}
	return 0
}

func (x *ChatResponse) GetFromCache() bool {
	if x != nil {
		return x.FromCache
	}
	return false
}

type MaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaskRequest) Reset() {
	*x = MaskRequest{}
	mi := &file_internal_pb_contextiq_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaskRequest) ProtoMessage() {}

func (x *MaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_contextiq_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaskRequest.ProtoReflect.Descriptor instead.
func (*MaskRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_contextiq_proto_rawDescGZIP(), []int{6}
}

func (x *MaskRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type MaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaskedText    string                 `protobuf:"bytes,1,opt,name=masked_text,json=maskedText,proto3" json:"masked_text,omitempty"`
	ItemsMasked   int32                  `protobuf:"varint,2,opt,name=items_masked,json=itemsMasked,proto3" json:"items_masked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaskResponse) Reset() {
	*x = MaskResponse{}
	mi := &file_internal_pb_contextiq_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaskResponse) ProtoMessage() {}

func (x *MaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_contextiq_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaskResponse.ProtoReflect.Descriptor instead.
func (*MaskResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_contextiq_proto_rawDescGZIP(), []int{7}
}

func (x *MaskResponse) GetMaskedText() string {
	if x != nil {
		return x.MaskedText
	}
	return ""
}

func (x *MaskResponse) GetItemsMasked() int32 {
	if x != nil {
		return x.ItemsMasked
	}
	return 0
}

var File_internal_pb_contextiq_proto protoreflect.FileDescriptor

const file_internal_pb_contextiq_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/pb/contextiq.proto\x12\tcontextiq\"+\n" +
	"\fIndexRequest\x12\x1b\n" +
	"\trepo_path\x18\x01 \x01(\tR\brepoPath\"\x91\x01\n" +
	"\rIndexResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rfiles_indexed\x18\x03 \x01(\x05R\ffilesIndexed\x12'\n" +
	"\x0fsymbols_indexed\x18\x04 \x01(\x05R\x0esymbolsIndexed\"\xc4\x01\n" +
	"\x0fOptimizeRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"open_files\x18\x02 \x03(\tR\topenFiles\x12\x1f\n" +
	"\vcursor_file\x18\x03 \x01(\tR\n" +
	"cursorFile\x12\x1f\n" +
	"\vcursor_line\x18\x04 \x01(\x05R\n" +
	"cursorLine\x12\x1b\n" +
	"\trepo_path\x18\x05 \x01(\tR\brepoPath\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x06 \x01(\x05R\tmaxTokens\"\xd9\x01\n" +
	"\x10OptimizeResponse\x12+\n" +
	"\x11compressed_prompt\x18\x01 \x01(\tR\x10compressedPrompt\x12#\n" +
	"\rtoken_savings\x18\x02 \x01(\x01R\ftokenSavings\x12\x1d\n" +
	"\n" +
	"raw_tokens\x18\x03 \x01(\x05R\trawTokens\x12)\n" +
	"\x10optimized_tokens\x18\x04 \x01(\x05R\x0foptimizedTokens\x12)\n" +
	"\x10included_symbols\x18\x05 \x03(\tR\x0fincludedSymbols\"\xf2\x01\n" +
	"\vChatRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"open_files\x18\x04 \x03(\tR\topenFiles\x12\x1f\n" +
	"\vcursor_file\x18\x05 \x01(\tR\n" +
	"cursorFile\x12\x1f\n" +
	"\vcursor_line\x18\x06 \x01(\x05R\n" +
	"cursorLine\x12\x1b\n" +
	"\trepo_path\x18\a \x01(\tR\brepoPath\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\b \x01(\x05R\tmaxTokens\"\xb8\x01\n" +
	"\fChatResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\x12)\n" +
	"\x10optimized_tokens\x18\x02 \x01(\x05R\x0foptimizedTokens\x12\x1d\n" +
	"\n" +
	"raw_tokens\x18\x03 \x01(\x05R\trawTokens\x12#\n" +
	"\rtoken_savings\x18\x04 \x01(\x01R\ftokenSavings\x12\x1d\n" +
	"\n" +
	"from_cache\x18\x05 \x01(\bR\tfromCache\"!\n" +
	"\vMaskRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"R\n" +
	"\fMaskResponse\x12\x1f\n" +
	"\vmasked_text\x18\x01 \x01(\tR\n" +
	"maskedText\x12!\n" +
	"\fitems_masked\x18\x02 \x01(\x05R\vitemsMasked2\x83\x02\n" +
	"\x0eContextService\x12:\n" +
	"\x05Index\x12\x17.contextiq.IndexRequest\x1a\x18.contextiq.IndexResponse\x12C\n" +
	"\bOptimize\x12\x1a.contextiq.OptimizeRequest\x1a\x1b.contextiq.OptimizeResponse\x127\n" +
	"\x04Chat\x12\x16.contextiq.ChatRequest\x1a\x17.contextiq.ChatResponse\x127\n" +
	"\x04Mask\x12\x16.contextiq.MaskRequest\x1a\x17.contextiq.MaskResponseB*Z(github.com/example/contextiq/internal/pbb\x06proto3"

var (
	file_internal_pb_contextiq_proto_rawDescOnce sync.Once
	file_internal_pb_contextiq_proto_rawDescData []byte
)

func file_internal_pb_contextiq_proto_rawDescGZIP() []byte {
	file_internal_pb_contextiq_proto_rawDescOnce.Do(func() {
		file_internal_pb_contextiq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_contextiq_proto_rawDesc), len(file_internal_pb_contextiq_proto_rawDesc)))
	})
	return file_internal_pb_contextiq_proto_rawDescData
}

var file_internal_pb_contextiq_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_pb_contextiq_proto_goTypes = []any{
	(*IndexRequest)(nil),     // 0: contextiq.IndexRequest
	(*IndexResponse)(nil),    // 1: contextiq.IndexResponse
	(*OptimizeRequest)(nil),  // 2: contextiq.OptimizeRequest
	(*OptimizeResponse)(nil), // 3: contextiq.OptimizeResponse
	(*ChatRequest)(nil),      // 4: contextiq.ChatRequest
	(*ChatResponse)(nil),     // 5: contextiq.ChatResponse
	(*MaskRequest)(nil),      // 6: contextiq.MaskRequest
	(*MaskResponse)(nil),     // 7: contextiq.MaskResponse
}
var file_internal_pb_contextiq_proto_depIdxs = []int32{
	0, // 0: contextiq.ContextService.Index:input_type -> contextiq.IndexRequest
	2, // 1: contextiq.ContextService.Optimize:input_type -> contextiq.OptimizeRequest
	4, // 2: contextiq.ContextService.Chat:input_type -> contextiq.ChatRequest
	6, // 3: contextiq.ContextService.Mask:input_type -> contextiq.MaskRequest
	1, // 4: contextiq.ContextService.Index:output_type -> contextiq.IndexResponse
	3, // 5: contextiq.ContextService.Optimize:output_type -> contextiq.OptimizeResponse
	5, // 6: contextiq.ContextService.Chat:output_type -> contextiq.ChatResponse
	7, // 7: contextiq.ContextService.Mask:output_type -> contextiq.MaskResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_pb_contextiq_proto_init() }
func file_internal_pb_contextiq_proto_init() {
	if File_internal_pb_contextiq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_contextiq_proto_rawDesc), len(file_internal_pb_contextiq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pb_contextiq_proto_goTypes,
		DependencyIndexes: file_internal_pb_contextiq_proto_depIdxs,
		MessageInfos:      file_internal_pb_contextiq_proto_msgTypes,
	}.Build()
	File_internal_pb_contextiq_proto = out.File
	file_internal_pb_contextiq_proto_goTypes = nil
	file_internal_pb_contextiq_proto_depIdxs = nil
}
